// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCArNvTwn98NinLSLXCrg710sYKS7ZNzJw',
    appId: '1:786077040761:web:4508c7ba182cd6a7ef94a8',
    messagingSenderId: '786077040761',
    projectId: 'truthordare-gamecard',
    authDomain: 'truthordare-gamecard.firebaseapp.com',
    storageBucket: 'truthordare-gamecard.firebasestorage.app',
    measurementId: 'G-TLN2K6S3HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYv8B2gnU7ubutK4jWi_u3-q-hk4tmPCs',
    appId: '1:786077040761:android:79a9a14cc2a57801ef94a8',
    messagingSenderId: '786077040761',
    projectId: 'truthordare-gamecard',
    storageBucket: 'truthordare-gamecard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2DP7eGjYr4ca859qsGTpIgcJadO3VcXk',
    appId: '1:786077040761:ios:7e6e3b8b9e890f56ef94a8',
    messagingSenderId: '786077040761',
    projectId: 'truthordare-gamecard',
    storageBucket: 'truthordare-gamecard.firebasestorage.app',
    iosBundleId: 'com.example.truthordare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2DP7eGjYr4ca859qsGTpIgcJadO3VcXk',
    appId: '1:786077040761:ios:7e6e3b8b9e890f56ef94a8',
    messagingSenderId: '786077040761',
    projectId: 'truthordare-gamecard',
    storageBucket: 'truthordare-gamecard.firebasestorage.app',
    iosBundleId: 'com.example.truthordare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCArNvTwn98NinLSLXCrg710sYKS7ZNzJw',
    appId: '1:786077040761:web:b54708281d733a1eef94a8',
    messagingSenderId: '786077040761',
    projectId: 'truthordare-gamecard',
    authDomain: 'truthordare-gamecard.firebaseapp.com',
    storageBucket: 'truthordare-gamecard.firebasestorage.app',
    measurementId: 'G-KBQ00LZVCX',
  );
}
